### PR TITLE
Fix bug:  the result will be incorrect when call gin.Context.Writer.Status() in our custom gin middleware used after this middleware

### PR DESCRIPTION
**Pull request by zhyee**
consider this code:

```go
func Timeout() gin.HandlerFunc {
	return timeout.New(timeout.WithTimeout(time.Second*1),
		timeout.WithHandler(func(ctx *gin.Context) {
			ctx.Next()
		}),
		timeout.WithResponse(func(ctx *gin.Context) {
			ctx.String(http.StatusRequestTimeout, "timeout")
		}),
	)
}

func Logger() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Next()
		// access the status we are sending
		status := c.Writer.Status() // Bug: in any middleware used after this middleware, the result will always be 200.
		log.Println(status)
	}
}

func main() {
	r := gin.New()
	r.Use(Timeout())
	r.Use(Logger())

	r.GET("/test", func(c *gin.Context) {
		c.Status(http.StatusInternalServerError)
	})
	// Listen and serve on 0.0.0.0:8080
	r.Run(":8080")
}
```

### CODE REVIEW

**Comment by zhyee** [comment]
issue: #47

**Comment by bramsvs** [comment]
@zhyee @appleboy any chance this can be reviewed & merged? :)

**Comment by millotp** [comment]
Hey, this would solve a bug for us too, can we get an update on this ?

**Comment by zhyee** [comment]
@appleboy Hi, I added a unit test to cover this bug fix, hope to be reviewed.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
can't pass the testing @zhyee

**Comment by appleboy** [comment]
I created the PR #61

**Pull request merged**
